"""
FAA Wildlife Strike — Damage Risk API (FastAPI)

Run with:  uvicorn api:app --reload --port 8000
Docs at:   http://localhost:8000/docs   (auto-generated by FastAPI/Swagger)

POST /predict with a JSON body matching StrikeInput to get back a damage
probability, using the exact same encoding pipeline as the Streamlit app
(both import from pipeline.py).
"""

from typing import Literal

from fastapi import FastAPI
from pydantic import BaseModel, Field

from pipeline import DEFAULT_THRESHOLD, predict

app = FastAPI(
    title="FAA Wildlife Strike Damage Risk API",
    description="Predicts whether a wildlife strike incident is likely to cause aircraft damage.",
    version="1.0.0",
)


class StrikeInput(BaseModel):
    AC_CLASS: Literal["A", "B", "C", "J", "Y", "Missing"] = "A"
    AC_MASS: Literal[1, 2, 3, 4, 5] = 4
    TYPE_ENG: Literal["A", "B", "C", "D", "E", "F", "Y", "Missing"] = "D"
    NUM_ENGS: Literal[1, 2, 3, 4] = 2

    PHASE_OF_FLIGHT: str = Field("Approach", description="e.g. Approach, Climb, En Route, Parked, Taxi...")
    HEIGHT: float = Field(500, ge=0, le=32000, description="Feet above ground level")
    SPEED: float = Field(140, ge=0, le=541, description="Knots")
    DISTANCE: float = Field(1.0, ge=0, le=200, description="Nautical miles from airport")

    INCIDENT_MONTH: int = Field(9, ge=1, le=12)
    INCIDENT_YEAR: int = Field(2026, ge=1990, le=2030)
    HOUR: int = Field(12, ge=0, le=23)
    TIME_OF_DAY: Literal["Day", "Night", "Dawn", "Dusk", "Missing"] = "Day"

    SKY: Literal["No Cloud", "Some Cloud", "Overcast", "Missing"] = "No Cloud"
    IS_FOG: bool = False
    IS_RAIN: bool = False
    IS_SNOW: bool = False

    SPECIES: str = Field("Unknown bird", description="Must match a species name from training data")
    SIZE: Literal["Small", "Medium", "Large", "Missing"] = "Medium"
    seen_reported: bool = Field(True, description="Was the number of animals seen actually reported?")
    NUM_SEEN_ORDINAL: int = Field(1, ge=0, le=4, description="0=not reported,1=1,2=2-10,3=11-100,4=100+")
    NUM_STRUCK_ORDINAL: int = Field(1, ge=1, le=4, description="1=1,2=2-10,3=11-100,4=100+")

    STATE: str = Field("CA", description="Two-letter US state code")
    FAAREGION: Literal["AAL", "ACE", "AEA", "AGL", "ANE", "ANM", "ASO", "ASW", "AWP", "FGN", "Missing"] = "AWP"

    threshold: float = Field(DEFAULT_THRESHOLD, ge=0, le=1, description="Decision threshold")


class StrikeOutput(BaseModel):
    damage_probability: float
    threshold_used: float
    predicted_damage: bool


@app.get("/")
def root():
    return {"status": "ok", "message": "POST /predict to get a damage-risk prediction. See /docs for the schema."}


@app.get("/health")
def health():
    return {"status": "healthy"}


@app.post("/predict", response_model=StrikeOutput)
def predict_damage(payload: StrikeInput):
    raw = payload.model_dump()
    threshold = raw.pop("threshold")
    return predict(raw, threshold=threshold)
